export const COUNTRY_FLAGS_AND_DIAL_CODES = [
    { name: 'Afghanistan', code: 'AF', dialCode: '+93', flagUrl: 'https://flagcdn.com/af.svg' },
    { name: 'Albania', code: 'AL', dialCode: '+355', flagUrl: 'https://flagcdn.com/al.svg' },
    { name: 'Algeria', code: 'DZ', dialCode: '+213', flagUrl: 'https://flagcdn.com/dz.svg' },
    { name: 'Andorra', code: 'AD', dialCode: '+376', flagUrl: 'https://flagcdn.com/ad.svg' },
    { name: 'Angola', code: 'AO', dialCode: '+244', flagUrl: 'https://flagcdn.com/ao.svg' },
    { name: 'Antigua and Barbuda', code: 'AG', dialCode: '+1-268', flagUrl: 'https://flagcdn.com/ag.svg' },
    { name: 'Argentina', code: 'AR', dialCode: '+54', flagUrl: 'https://flagcdn.com/ar.svg' },
    { name: 'Armenia', code: 'AM', dialCode: '+374', flagUrl: 'https://flagcdn.com/am.svg' },
    { name: 'Australia', code: 'AU', dialCode: '+61', flagUrl: 'https://flagcdn.com/au.svg' },
    { name: 'Austria', code: 'AT', dialCode: '+43', flagUrl: 'https://flagcdn.com/at.svg' },
    { name: 'Azerbaijan', code: 'AZ', dialCode: '+994', flagUrl: 'https://flagcdn.com/az.svg' },
    { name: 'Bahamas', code: 'BS', dialCode: '+1-242', flagUrl: 'https://flagcdn.com/bs.svg' },
    { name: 'Bahrain', code: 'BH', dialCode: '+973', flagUrl: 'https://flagcdn.com/bh.svg' },
    { name: 'Bangladesh', code: 'BD', dialCode: '+880', flagUrl: 'https://flagcdn.com/bd.svg' },
    { name: 'Barbados', code: 'BB', dialCode: '+1-246', flagUrl: 'https://flagcdn.com/bb.svg' },
    { name: 'Belarus', code: 'BY', dialCode: '+375', flagUrl: 'https://flagcdn.com/by.svg' },
    { name: 'Belgium', code: 'BE', dialCode: '+32', flagUrl: 'https://flagcdn.com/be.svg' },
    { name: 'Belize', code: 'BZ', dialCode: '+501', flagUrl: 'https://flagcdn.com/bz.svg' },
    { name: 'Benin', code: 'BJ', dialCode: '+229', flagUrl: 'https://flagcdn.com/bj.svg' },
    { name: 'Bhutan', code: 'BT', dialCode: '+975', flagUrl: 'https://flagcdn.com/bt.svg' },
    { name: 'Bolivia', code: 'BO', dialCode: '+591', flagUrl: 'https://flagcdn.com/bo.svg' },
    { name: 'Bosnia and Herzegovina', code: 'BA', dialCode: '+387', flagUrl: 'https://flagcdn.com/ba.svg' },
    { name: 'Botswana', code: 'BW', dialCode: '+267', flagUrl: 'https://flagcdn.com/bw.svg' },
    { name: 'Brazil', code: 'BR', dialCode: '+55', flagUrl: 'https://flagcdn.com/br.svg' },
    { name: 'Brunei', code: 'BN', dialCode: '+673', flagUrl: 'https://flagcdn.com/bn.svg' },
    { name: 'Bulgaria', code: 'BG', dialCode: '+359', flagUrl: 'https://flagcdn.com/bg.svg' },
    { name: 'Burkina Faso', code: 'BF', dialCode: '+226', flagUrl: 'https://flagcdn.com/bf.svg' },
    { name: 'Burundi', code: 'BI', dialCode: '+257', flagUrl: 'https://flagcdn.com/bi.svg' },
    { name: 'Cabo Verde', code: 'CV', dialCode: '+238', flagUrl: 'https://flagcdn.com/cv.svg' },
    { name: 'Cambodia', code: 'KH', dialCode: '+855', flagUrl: 'https://flagcdn.com/kh.svg' },
    { name: 'Cameroon', code: 'CM', dialCode: '+237', flagUrl: 'https://flagcdn.com/cm.svg' },
    { name: 'Canada', code: 'CA', dialCode: '+1', flagUrl: 'https://flagcdn.com/ca.svg' },
    { name: 'Central African Republic', code: 'CF', dialCode: '+236', flagUrl: 'https://flagcdn.com/cf.svg' },
    { name: 'Chad', code: 'TD', dialCode: '+235', flagUrl: 'https://flagcdn.com/td.svg' },
    { name: 'Chile', code: 'CL', dialCode: '+56', flagUrl: 'https://flagcdn.com/cl.svg' },
    { name: 'China', code: 'CN', dialCode: '+86', flagUrl: 'https://flagcdn.com/cn.svg' },
    { name: 'Colombia', code: 'CO', dialCode: '+57', flagUrl: 'https://flagcdn.com/co.svg' },
    { name: 'Comoros', code: 'KM', dialCode: '+269', flagUrl: 'https://flagcdn.com/km.svg' },
    { name: 'Congo (Brazzaville)', code: 'CG', dialCode: '+242', flagUrl: 'https://flagcdn.com/cg.svg' },
    { name: 'Congo (Kinshasa)', code: 'CD', dialCode: '+243', flagUrl: 'https://flagcdn.com/cd.svg' },
    { name: 'Costa Rica', code: 'CR', dialCode: '+506', flagUrl: 'https://flagcdn.com/cr.svg' },
    { name: 'Côte d\'Ivoire', code: 'CI', dialCode: '+225', flagUrl: 'https://flagcdn.com/ci.svg' },
    { name: 'Croatia', code: 'HR', dialCode: '+385', flagUrl: 'https://flagcdn.com/hr.svg' },
    { name: 'Cuba', code: 'CU', dialCode: '+53', flagUrl: 'https://flagcdn.com/cu.svg' },
    { name: 'Cyprus', code: 'CY', dialCode: '+357', flagUrl: 'https://flagcdn.com/cy.svg' },
    { name: 'Czech Republic', code: 'CZ', dialCode: '+420', flagUrl: 'https://flagcdn.com/cz.svg' },
    { name: 'Denmark', code: 'DK', dialCode: '+45', flagUrl: 'https://flagcdn.com/dk.svg' },
    { name: 'Djibouti', code: 'DJ', dialCode: '+253', flagUrl: 'https://flagcdn.com/dj.svg' },
    { name: 'Dominica', code: 'DM', dialCode: '+1-767', flagUrl: 'https://flagcdn.com/dm.svg' },
    { name: 'Dominican Republic', code: 'DO', dialCode: '+1-809', flagUrl: 'https://flagcdn.com/do.svg' },
    { name: 'Ecuador', code: 'EC', dialCode: '+593', flagUrl: 'https://flagcdn.com/ec.svg' },
    { name: 'Egypt', code: 'EG', dialCode: '+20', flagUrl: 'https://flagcdn.com/eg.svg' },
    { name: 'El Salvador', code: 'SV', dialCode: '+503', flagUrl: 'https://flagcdn.com/sv.svg' },
    { name: 'Equatorial Guinea', code: 'GQ', dialCode: '+240', flagUrl: 'https://flagcdn.com/gq.svg' },
    { name: 'Eritrea', code: 'ER', dialCode: '+291', flagUrl: 'https://flagcdn.com/er.svg' },
    { name: 'Estonia', code: 'EE', dialCode: '+372', flagUrl: 'https://flagcdn.com/ee.svg' },
    { name: 'Eswatini', code: 'SZ', dialCode: '+268', flagUrl: 'https://flagcdn.com/sz.svg' },
    { name: 'Ethiopia', code: 'ET', dialCode: '+251', flagUrl: 'https://flagcdn.com/et.svg' },
    { name: 'Fiji', code: 'FJ', dialCode: '+679', flagUrl: 'https://flagcdn.com/fj.svg' },
    { name: 'Finland', code: 'FI', dialCode: '+358', flagUrl: 'https://flagcdn.com/fi.svg' },
    { name: 'France', code: 'FR', dialCode: '+33', flagUrl: 'https://flagcdn.com/fr.svg' },
    { name: 'Gabon', code: 'GA', dialCode: '+241', flagUrl: 'https://flagcdn.com/ga.svg' },
    { name: 'Gambia', code: 'GM', dialCode: '+220', flagUrl: 'https://flagcdn.com/gm.svg' },
    { name: 'Georgia', code: 'GE', dialCode: '+995', flagUrl: 'https://flagcdn.com/ge.svg' },
    { name: 'Germany', code: 'DE', dialCode: '+49', flagUrl: 'https://flagcdn.com/de.svg' },
    { name: 'Ghana', code: 'GH', dialCode: '+233', flagUrl: 'https://flagcdn.com/gh.svg' },
    { name: 'Greece', code: 'GR', dialCode: '+30', flagUrl: 'https://flagcdn.com/gr.svg' },
    { name: 'Grenada', code: 'GD', dialCode: '+1-473', flagUrl: 'https://flagcdn.com/gd.svg' },
    { name: 'Guatemala', code: 'GT', dialCode: '+502', flagUrl: 'https://flagcdn.com/gt.svg' },
    { name: 'Guinea', code: 'GN', dialCode: '+224', flagUrl: 'https://flagcdn.com/gn.svg' },
    { name: 'Guinea-Bissau', code: 'GW', dialCode: '+245', flagUrl: 'https://flagcdn.com/gw.svg' },
    { name: 'Guyana', code: 'GY', dialCode: '+592', flagUrl: 'https://flagcdn.com/gy.svg' },
    { name: 'Haiti', code: 'HT', dialCode: '+509', flagUrl: 'https://flagcdn.com/ht.svg' },
    { name: 'Honduras', code: 'HN', dialCode: '+504', flagUrl: 'https://flagcdn.com/hn.svg' },
    { name: 'Hungary', code: 'HU', dialCode: '+36', flagUrl: 'https://flagcdn.com/hu.svg' },
    { name: 'Iceland', code: 'IS', dialCode: '+354', flagUrl: 'https://flagcdn.com/is.svg' },
    { name: 'India', code: 'IN', dialCode: '+91', flagUrl: 'https://flagcdn.com/in.svg' },
    { name: 'Indonesia', code: 'ID', dialCode: '+62', flagUrl: 'https://flagcdn.com/id.svg' },
    { name: 'Iran', code: 'IR', dialCode: '+98', flagUrl: 'https://flagcdn.com/ir.svg' },
    { name: 'Iraq', code: 'IQ', dialCode: '+964', flagUrl: 'https://flagcdn.com/iq.svg' },
    { name: 'Ireland', code: 'IE', dialCode: '+353', flagUrl: 'https://flagcdn.com/ie.svg' },
    { name: 'Israel', code: 'IL', dialCode: '+972', flagUrl: 'https://flagcdn.com/il.svg' },
    { name: 'Italy', code: 'IT', dialCode: '+39', flagUrl: 'https://flagcdn.com/it.svg' },
    { name: 'Jamaica', code: 'JM', dialCode: '+1-876', flagUrl: 'https://flagcdn.com/jm.svg' },
    { name: 'Japan', code: 'JP', dialCode: '+81', flagUrl: 'https://flagcdn.com/jp.svg' },
    { name: 'Jordan', code: 'JO', dialCode: '+962', flagUrl: 'https://flagcdn.com/jo.svg' },
    { name: 'Kazakhstan', code: 'KZ', dialCode: '+7', flagUrl: 'https://flagcdn.com/kz.svg' },
    { name: 'Kenya', code: 'KE', dialCode: '+254', flagUrl: 'https://flagcdn.com/ke.svg' },
    { name: 'Kiribati', code: 'KI', dialCode: '+686', flagUrl: 'https://flagcdn.com/ki.svg' },
    { name: 'Kuwait', code: 'KW', dialCode: '+965', flagUrl: 'https://flagcdn.com/kw.svg' },
    { name: 'Kyrgyzstan', code: 'KG', dialCode: '+996', flagUrl: 'https://flagcdn.com/kg.svg' },
    { name: 'Laos', code: 'LA', dialCode: '+856', flagUrl: 'https://flagcdn.com/la.svg' },
    { name: 'Latvia', code: 'LV', dialCode: '+371', flagUrl: 'https://flagcdn.com/lv.svg' },
    { name: 'Lebanon', code: 'LB', dialCode: '+961', flagUrl: 'https://flagcdn.com/lb.svg' },
    { name: 'Lesotho', code: 'LS', dialCode: '+266', flagUrl: 'https://flagcdn.com/ls.svg' },
    { name: 'Liberia', code: 'LR', dialCode: '+231', flagUrl: 'https://flagcdn.com/lr.svg' },
    { name: 'Libya', code: 'LY', dialCode: '+218', flagUrl: 'https://flagcdn.com/ly.svg' },
    { name: 'Liechtenstein', code: 'LI', dialCode: '+423', flagUrl: 'https://flagcdn.com/li.svg' },
    { name: 'Lithuania', code: 'LT', dialCode: '+370', flagUrl: 'https://flagcdn.com/lt.svg' },
    { name: 'Luxembourg', code: 'LU', dialCode: '+352', flagUrl: 'https://flagcdn.com/lu.svg' },
    { name: 'Madagascar', code: 'MG', dialCode: '+261', flagUrl: 'https://flagcdn.com/mg.svg' },
    { name: 'Malawi', code: 'MW', dialCode: '+265', flagUrl: 'https://flagcdn.com/mw.svg' },
    { name: 'Malaysia', code: 'MY', dialCode: '+60', flagUrl: 'https://flagcdn.com/my.svg' },
    { name: 'Maldives', code: 'MV', dialCode: '+960', flagUrl: 'https://flagcdn.com/mv.svg' },
    { name: 'Mali', code: 'ML', dialCode: '+223', flagUrl: 'https://flagcdn.com/ml.svg' },
    { name: 'Malta', code: 'MT', dialCode: '+356', flagUrl: 'https://flagcdn.com/mt.svg' },
    { name: 'Marshall Islands', code: 'MH', dialCode: '+692', flagUrl: 'https://flagcdn.com/mh.svg' },
    { name: 'Mauritania', code: 'MR', dialCode: '+222', flagUrl: 'https://flagcdn.com/mr.svg' },
    { name: 'Mauritius', code: 'MU', dialCode: '+230', flagUrl: 'https://flagcdn.com/mu.svg' },
    { name: 'Mexico', code: 'MX', dialCode: '+52', flagUrl: 'https://flagcdn.com/mx.svg' },
    { name: 'Micronesia', code: 'FM', dialCode: '+691', flagUrl: 'https://flagcdn.com/fm.svg' },
    { name: 'Moldova', code: 'MD', dialCode: '+373', flagUrl: 'https://flagcdn.com/md.svg' },
    { name: 'Monaco', code: 'MC', dialCode: '+377', flagUrl: 'https://flagcdn.com/mc.svg' },
    { name: 'Mongolia', code: 'MN', dialCode: '+976', flagUrl: 'https://flagcdn.com/mn.svg' },
    { name: 'Montenegro', code: 'ME', dialCode: '+382', flagUrl: 'https://flagcdn.com/me.svg' },
    { name: 'Morocco', code: 'MA', dialCode: '+212', flagUrl: 'https://flagcdn.com/ma.svg' },
    { name: 'Mozambique', code: 'MZ', dialCode: '+258', flagUrl: 'https://flagcdn.com/mz.svg' },
    { name: 'Myanmar', code: 'MM', dialCode: '+95', flagUrl: 'https://flagcdn.com/mm.svg' },
    { name: 'Namibia', code: 'NA', dialCode: '+264', flagUrl: 'https://flagcdn.com/na.svg' },
    { name: 'Nauru', code: 'NR', dialCode: '+674', flagUrl: 'https://flagcdn.com/nr.svg' },
    { name: 'Nepal', code: 'NP', dialCode: '+977', flagUrl: 'https://flagcdn.com/np.svg' },
    { name: 'Netherlands', code: 'NL', dialCode: '+31', flagUrl: 'https://flagcdn.com/nl.svg' },
    { name: 'New Zealand', code: 'NZ', dialCode: '+64', flagUrl: 'https://flagcdn.com/nz.svg' },
    { name: 'Nicaragua', code: 'NI', dialCode: '+505', flagUrl: 'https://flagcdn.com/ni.svg' },
    { name: 'Niger', code: 'NE', dialCode: '+227', flagUrl: 'https://flagcdn.com/ne.svg' },
    { name: 'Nigeria', code: 'NG', dialCode: '+234', flagUrl: 'https://flagcdn.com/ng.svg' },
    { name: 'North Korea', code: 'KP', dialCode: '+850', flagUrl: 'https://flagcdn.com/kp.svg' },
    { name: 'North Macedonia', code: 'MK', dialCode: '+389', flagUrl: 'https://flagcdn.com/mk.svg' },
    { name: 'Norway', code: 'NO', dialCode: '+47', flagUrl: 'https://flagcdn.com/no.svg' },
    { name: 'Oman', code: 'OM', dialCode: '+968', flagUrl: 'https://flagcdn.com/om.svg' },
    { name: 'Pakistan', code: 'PK', dialCode: '+92', flagUrl: 'https://flagcdn.com/pk.svg' },
    { name: 'Palau', code: 'PW', dialCode: '+680', flagUrl: 'https://flagcdn.com/pw.svg' },
    { name: 'Palestine', code: 'PS', dialCode: '+970', flagUrl: 'https://flagcdn.com/ps.svg' },
    { name: 'Panama', code: 'PA', dialCode: '+507', flagUrl: 'https://flagcdn.com/pa.svg' },
    { name: 'Papua New Guinea', code: 'PG', dialCode: '+675', flagUrl: 'https://flagcdn.com/pg.svg' },
    { name: 'Paraguay', code: 'PY', dialCode: '+595', flagUrl: 'https://flagcdn.com/py.svg' },
    { name: 'Peru', code: 'PE', dialCode: '+51', flagUrl: 'https://flagcdn.com/pe.svg' },
    { name: 'Philippines', code: 'PH', dialCode: '+63', flagUrl: 'https://flagcdn.com/ph.svg' },
    { name: 'Poland', code: 'PL', dialCode: '+48', flagUrl: 'https://flagcdn.com/pl.svg' },
    { name: 'Portugal', code: 'PT', dialCode: '+351', flagUrl: 'https://flagcdn.com/pt.svg' },
    { name: 'Qatar', code: 'QA', dialCode: '+974', flagUrl: 'https://flagcdn.com/qa.svg' },
    { name: 'Romania', code: 'RO', dialCode: '+40', flagUrl: 'https://flagcdn.com/ro.svg' },
    { name: 'Russia', code: 'RU', dialCode: '+7', flagUrl: 'https://flagcdn.com/ru.svg' },
    { name: 'Rwanda', code: 'RW', dialCode: '+250', flagUrl: 'https://flagcdn.com/rw.svg' },
    { name: 'Saint Kitts and Nevis', code: 'KN', dialCode: '+1-869', flagUrl: 'https://flagcdn.com/kn.svg' },
    { name: 'Saint Lucia', code: 'LC', dialCode: '+1-758', flagUrl: 'https://flagcdn.com/lc.svg' },
    { name: 'Saint Vincent and the Grenadines', code: 'VC', dialCode: '+1-784', flagUrl: 'https://flagcdn.com/vc.svg' },
    { name: 'Samoa', code: 'WS', dialCode: '+685', flagUrl: 'https://flagcdn.com/ws.svg' },
    { name: 'San Marino', code: 'SM', dialCode: '+378', flagUrl: 'https://flagcdn.com/sm.svg' },
    { name: 'Sao Tome and Principe', code: 'ST', dialCode: '+239', flagUrl: 'https://flagcdn.com/st.svg' },
    { name: 'Saudi Arabia', code: 'SA', dialCode: '+966', flagUrl: 'https://flagcdn.com/sa.svg' },
    { name: 'Senegal', code: 'SN', dialCode: '+221', flagUrl: 'https://flagcdn.com/sn.svg' },
    { name: 'Serbia', code: 'RS', dialCode: '+381', flagUrl: 'https://flagcdn.com/rs.svg' },
    { name: 'Seychelles', code: 'SC', dialCode: '+248', flagUrl: 'https://flagcdn.com/sc.svg' },
    { name: 'Sierra Leone', code: 'SL', dialCode: '+232', flagUrl: 'https://flagcdn.com/sl.svg' },
    { name: 'Singapore', code: 'SG', dialCode: '+65', flagUrl: 'https://flagcdn.com/sg.svg' },
    { name: 'Slovakia', code: 'SK', dialCode: '+421', flagUrl: 'https://flagcdn.com/sk.svg' },
    { name: 'Slovenia', code: 'SI', dialCode: '+386', flagUrl: 'https://flagcdn.com/si.svg' },
    { name: 'Solomon Islands', code: 'SB', dialCode: '+677', flagUrl: 'https://flagcdn.com/sb.svg' },
    { name: 'Somalia', code: 'SO', dialCode: '+252', flagUrl: 'https://flagcdn.com/so.svg' },
    { name: 'South Africa', code: 'ZA', dialCode: '+27', flagUrl: 'https://flagcdn.com/za.svg' },
    { name: 'South Korea', code: 'KR', dialCode: '+82', flagUrl: 'https://flagcdn.com/kr.svg' },
    { name: 'South Sudan', code: 'SS', dialCode: '+211', flagUrl: 'https://flagcdn.com/ss.svg' },
    { name: 'Spain', code: 'ES', dialCode: '+34', flagUrl: 'https://flagcdn.com/es.svg' },
    { name: 'Sri Lanka', code: 'LK', dialCode: '+94', flagUrl: 'https://flagcdn.com/lk.svg' },
    { name: 'Sudan', code: 'SD', dialCode: '+249', flagUrl: 'https://flagcdn.com/sd.svg' },
    { name: 'Suriname', code: 'SR', dialCode: '+597', flagUrl: 'https://flagcdn.com/sr.svg' },
    { name: 'Sweden', code: 'SE', dialCode: '+46', flagUrl: 'https://flagcdn.com/se.svg' },
    { name: 'Switzerland', code: 'CH', dialCode: '+41', flagUrl: 'https://flagcdn.com/ch.svg' },
    { name: 'Syria', code: 'SY', dialCode: '+963', flagUrl: 'https://flagcdn.com/sy.svg' },
    { name: 'Taiwan', code: 'TW', dialCode: '+886', flagUrl: 'https://flagcdn.com/tw.svg' },
    { name: 'Tajikistan', code: 'TJ', dialCode: '+992', flagUrl: 'https://flagcdn.com/tj.svg' },
    { name: 'Tanzania', code: 'TZ', dialCode: '+255', flagUrl: 'https://flagcdn.com/tz.svg' },
    { name: 'Thailand', code: 'TH', dialCode: '+66', flagUrl: 'https://flagcdn.com/th.svg' },
    { name: 'Timor-Leste', code: 'TL', dialCode: '+670', flagUrl: 'https://flagcdn.com/tl.svg' },
    { name: 'Togo', code: 'TG', dialCode: '+228', flagUrl: 'https://flagcdn.com/tg.svg' },
    { name: 'Tonga', code: 'TO', dialCode: '+676', flagUrl: 'https://flagcdn.com/to.svg' },
    { name: 'Trinidad and Tobago', code: 'TT', dialCode: '+1-868', flagUrl: 'https://flagcdn.com/tt.svg' },
    { name: 'Tunisia', code: 'TN', dialCode: '+216', flagUrl: 'https://flagcdn.com/tn.svg' },
    { name: 'Turkey', code: 'TR', dialCode: '+90', flagUrl: 'https://flagcdn.com/tr.svg' },
    { name: 'Turkmenistan', code: 'TM', dialCode: '+993', flagUrl: 'https://flagcdn.com/tm.svg' },
    { name: 'Tuvalu', code: 'TV', dialCode: '+688', flagUrl: 'https://flagcdn.com/tv.svg' },
    { name: 'Uganda', code: 'UG', dialCode: '+256', flagUrl: 'https://flagcdn.com/ug.svg' },
    { name: 'Ukraine', code: 'UA', dialCode: '+380', flagUrl: 'https://flagcdn.com/ua.svg' },
    { name: 'United Arab Emirates', code: 'AE', dialCode: '+971', flagUrl: 'https://flagcdn.com/ae.svg' },
    { name: 'United Kingdom', code: 'GB', dialCode: '+44', flagUrl: 'https://flagcdn.com/gb.svg' },
    { name: 'United States', code: 'US', dialCode: '+1', flagUrl: 'https://flagcdn.com/us.svg' },
    { name: 'Uruguay', code: 'UY', dialCode: '+598', flagUrl: 'https://flagcdn.com/uy.svg' },
    { name: 'Uzbekistan', code: 'UZ', dialCode: '+998', flagUrl: 'https://flagcdn.com/uz.svg' },
    { name: 'Vanuatu', code: 'VU', dialCode: '+678', flagUrl: 'https://flagcdn.com/vu.svg' },
    { name: 'Vatican City', code: 'VA', dialCode: '+379', flagUrl: 'https://flagcdn.com/va.svg' },
    { name: 'Venezuela', code: 'VE', dialCode: '+58', flagUrl: 'https://flagcdn.com/ve.svg' },
    { name: 'Vietnam', code: 'VN', dialCode: '+84', flagUrl: 'https://flagcdn.com/vn.svg' },
    { name: 'Yemen', code: 'YE', dialCode: '+967', flagUrl: 'https://flagcdn.com/ye.svg' },
    { name: 'Zambia', code: 'ZM', dialCode: '+260', flagUrl: 'https://flagcdn.com/zm.svg' },
    { name: 'Zimbabwe', code: 'ZW', dialCode: '+263', flagUrl: 'https://flagcdn.com/zw.svg' }
];
